[project]
name = "fastmcp-stremable-http-issue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "fastmcp>=2.3.5",
    "typer>=0.15.4",
    "uvicorn>=0.34.2",
]
